# Generated by Django 3.1.7 on 2021-03-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20210302_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='milestones',
            old_name='goal_id',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='missions',
            old_name='user_id',
            new_name='user',
        ),
    ]
