# Generated by Django 3.1.7 on 2021-04-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20210302_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
